
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bd_n?serverTimezone=UTC
    username: root
    password: "000000"
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhrx.entity
server:
  port: 9009
