mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhrx.entity


server:
  port: 9009
logging:
  config: classpath:log4j2.xml
  com.zhrx.MybatisApplication: WARN
spring:
  redis:
    jedis:
      pool:
        max-active: 10
        max-wait: 6000ms
        max-idle: 8
        min-idle: 5
    host: 127.0.0.1
    database: 1
    port: 6379




